.gitignore
README.md
merge_sort/Python/merge_sort.py
quicksort/Python/quicksort.py

rel https://github.com/NITSkmOS/Algorithms/issues/2

Add Quick Sort and Merge Sort Algo

---

README.md
insertion_sort/Python/insertion_sort.py

rel https://github.com/NITSkmOS/Algorithms/issues/2

insertion_sort: Add insertion sort algorithm

---

README.md

README: Add NITSkmOS badge

---

README.md
counting_sort/Python/counting_sort.py
radix_sort/Python/radix_sort.py

Radix and Counting Sort Algorithm

---

README.md
binary_search/Python/binary_search.py

This adds Binary Search Algorithm which returns the index
of key and return -1 if the key is not found in the array.
Closes https://github.com/NITSkmOS/Algorithms/issues/43

Add Binary Search Algorithm

---

insertion_sort/C++/insertion_sort.cpp

Added C++ code for Insertion Sort

---

linked_list/c/linked_list.c

This adds Algorithm for implementation of Linear Linked List Data Structure.Each
node is represented by struct data type that contains integer data for
storing integer data and a pointer that points to next node in the linked list.
Closes https://github.com/NITSkmOS/Algorithms/issues/26
Fixes #26 

linked_list.c Add Linear Linked List Implementation

---

README.md
bubble_sort/C++/bubble_sort.cpp

Add a simple C++ implementation of bubble sort
Closes https://github.com/NITSkmOS/Algorithms/issues/20

bubble_sort: Add C++ Implementation

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

CODE_OF_CONDUCT.md: Add CODE_OF_CONDUCT

---

quicksort/Python/quicksort.py

This corrects the spelling of 'function'.
Closes #95 

quicksort.py Spell check

---

README.md
binary_search/C++/binary_search.cpp
binary_search/Cpp/binary_search.cpp

This adds Binary Search Algorithm which returns the index of key(x) and
return -1 if the key is not found in the array.
Fixes #45 

Added Binary Search Algorithm and updated ReadMe

---

README.md
shell_sort/Python/shell_sort.py

This adds shell sort algorithm
Closes https://github.com/NITSkmOS/Algorithms/issues/133

shell_sort.py: Add Shell Sort Algorithm

---

.coafile
GIT_BASICS.md

This is git basic tutorial for this repository
for newcomers.
Closes #156

GIT_BASICS.md: Git Basic Documentation

---

README.md
avl_tree/Python/avl_tree.py

Adds the code for AVL Tree in Python

---

README.md
shell_sort/C/shell_sort.c

This implementation uses half of the array's size as the gap.
Then it keeps dividing it by 2.
Closes [#135](https://github.com/NITSkmOS/Algorithms/issues/135)  

shell_sort.c: Added Shell sort algorithm in C

---

bubble_sort/Cpp/bubble_sort.cpp

Optimized the initial C++ code.

Optimizing the initial C++ code

---

README.md

This removes Codacy badge and adds Travis badge to README.md file.
Closes https://github.com/NITSkmOS/Algorithms/issues/209

README.md: Remove codacy badge, Add travis badge

---

README.md
maximum_subarray/Python/max_sub_array.py

[https://github.com/NITSkmOS/Algorithms/issues/215](url)

Add Maximum SubArray Problem[Python]

---

README.md
knapsack_problem/Python/knapsack.py

closes [https://github.com/NITSkmOS/Algorithms/issues/305](url)

knapsack.py : Add KnapSack Problem 

---

README.md
linked_list/cpp/linked_list.cpp

This adds the singly linked list data structure in C++ langauge.
Singly linked list stores the value of a node as well as a pointer
to the next node. Utility functions for adding / deleting
as well as driver code is included.
Closes [#27](https://github.com/NITSkmOS/Algorithms/issues/27) 
After you submit your pull request, **DO NOT** click the 'Update …

linked_list.cpp : Add linked list in C++

---

stack/Python/stack.py

**Yes, that's me, thanks!**
Fixes #294 

Raise exception when popping from an empty stack #294

---

README.md
binary_search_tree/Cpp/binary_search_tree.cpp

This adds C++ implementation of binary search tree with search, insert and delete functions.
Closes https://github.com/NITSkmOS/Algorithms/issues/54

binary_search_tree.cpp: Add Binary search tree

---

README.md
fenwick_tree/java/FenwickTree.java
fenwick_tree/java/fenwick_tree.java

[Closes #218](https://github.com/NITSkmOS/Algorithms/issues/218)

fenwick_tree.java: Add Fenwick Tree Data Structure

---

README.md
fenwick_tree/Python/fenwick_tree.py

Add FenwickTree for Python

---

.travis.yml

Closes  https://github.com/NITSkmOS/Algorithms/issues/461

.travis.yml: Activate TravisBuddy

---

README.md
doubly_linked_list/c/doubly_linked_list.c

doubly_linked_list.c: Adds Doubly Linked List
This adds Doubly Linked List that can be traversed in both forward and
backward directions. There are functions that inserts nodes and prints
the list.
Closes https://github.com/NITSkmOS/Algorithms/issues/31
Fixes #31 

Add Doubly Linked List DS

---

README.md

New badges for README.md

---

README.md
fenwick_tree/cpp/fenwick_tree.cpp

Add fenwick_tree.cpp

---

CONTRIBUTING.md
GIT_BASICS.md
README.md

Fix #493: Switching from tabs to spaces in markdown

---

README.md

Correctly mapped the contributors count for NITSkmOS/Algorithms.
closes https://github.com/NITSkmOS/Algorithms/issues/495

README.md: Update badge

---

.coafile
.gitignore
.misc/apt_install.sh
.misc/npm_install.sh
.misc/pip3_install.sh
.travis.yml

.travis.yml: Fix Travis build

---

.misc/run_test.sh
.travis.yml
merge_sort/C/merge_sort.c

merge_sort.c: Fix stack smashing error

---

CONTRIBUTING.md
merge_sort/C/merge_sort.c

merge_sort.c: Fix Trap 6 error causing Travis break
